export const list = [
  { name: 'L-daoxu' },
  { name: 'L-zhengxu' },
  { name: 'L-shouye' },
  { name: 'L-wode' },
  { name: 'F-shouye' },
  { name: 'F-wode1' },
  { name: 'F-yang1' },
  { name: 'L-wancheng' },
  { name: 'L-shezhi' },
  { name: 'L-dianhua' },
  { name: 'F-jiantou-chengse' },
  { name: 'L-jiantou-chengse' },
  { name: 'L-mima' },
  { name: 'L-tianjia' },
  { name: 'L-shoujihao' },
  { name: 'L-yanzheng' },
  { name: 'F-xuetang1' },
  { name: 'L-kapian' },
  { name: 'L-zhengjian' },
  { name: 'F-zanting' },
  { name: 'F-zhengchang' },
  { name: 'F-bofang' },
  { name: 'F-guanbi' },
  { name: 'F-yichang2' },
  { name: 'F-duigou' },
  { name: 'F-fuzhen' },
  { name: 'F-jiantou1-you' },
  { name: 'F-jiantou1-xia' },
  { name: 'F-jiantou1-zuo' },
  { name: 'F-fengxianguanli' },
  { name: 'F-shangsheng' },
  { name: 'F-jingqiliuliang' },
  { name: 'F-rili' },
  { name: 'F-jingqi' },
  { name: 'F-gengduo' },
  { name: 'F-suifang' },
  { name: 'F-pailuan' },
  { name: 'F-shenghuofuwu' },
  { name: 'F-renwu' },
  { name: 'F-tongjing' },
  { name: 'F-tizhong' },
  { name: 'F-wode' },
  { name: 'F-shoucang' },
  { name: 'F-xiajiang' },
  { name: 'F-jiantou1-shang' },
  { name: 'F-xueya' },
  { name: 'F-tiwen' },
  { name: 'F-xiangji' },
  { name: 'F-gerenxinxi' },
  { name: 'F-yinliuguan' },
  { name: 'F-shezhi' },
  { name: 'F-xinqing' },
  { name: 'F-yinshi' },
  { name: 'F-yongyao' },
  { name: 'F-yinshui' },
  { name: 'F-yongyaotixing' },
  { name: 'F-tiwei' },
  { name: 'F-yichang' },
  { name: 'F-zhishi' },
  { name: 'F-zhoubao' },
  { name: 'F-zhengzhuang' },
  { name: 'F-yuebao' },
  { name: 'F-yundong' },
  { name: 'L-bianji' },
  { name: 'L-guanbi' },
  { name: 'L-jiantou2-shang-2' },
  { name: 'L-jiantou2-shang-1' },
  { name: 'L-fankui' },
  { name: 'L-jiantou1-xia' },
  { name: 'L-jiantou2-shang' },
  { name: 'L-jiantou1-shang' },
  { name: 'L-jiantou1-you' },
  { name: 'L-jiantou1-zuo' },
  { name: 'L-jiantou2-xia' },
  { name: 'L-shaixuan' },
  { name: 'L-shanchu' },
  { name: 'L-shoucang' },
  { name: 'L-shuoming' },
  { name: 'L-tixing' },
  { name: 'L-xiangji' },
  { name: 'L-yaoxiang' },
  { name: 'L-shebei' },
]

export const type = [
  'primary',
  'success',
  'info',
  'error',
  'warning'
]
